### ISSUE TITLE
Japanese characters in the TAGS page

### ISSUE THREAD

**Issue by HenriqueCSJ** [brennanbrown/enjoyment-work#11]
Thanks for the great theme!
As I can see, in the TAGS page we have Japanese characters (see below) marking each entry for each tag. Is there a way to change to Latin characters or regular bullet points/numbers?

![image](https://user-images.githubusercontent.com/574402/138685692-9b04f291-1793-422b-bf1c-8e9a16ea29d7.png)

**Comment by clarkedarkmatter** [comment]
I would like to change these as well.

**Comment by brennanbrown** [comment]
I'm very sorry for the late reply. It is now set to default!
